### ISSUE TITLE
Unable to create a token from the CLI even with proper access to the vault

### ISSUE THREAD

**Issue by arunsathiya** [1Password/connect#59]
Hi there! I am a new 1Password Connect user. Following the documentation on this GitHub README, I created a Connect Server (not deployed yet at this point) but creating a Token fails with the error: `Couldn't issue the token: "can't grant access to the vault: You do not have the requested access to vault`

```
➜  ~ op connect server create Connect --vaults redacted
File /Users/arun/1password-credentials.json already exists, overwrite it? [Y/n]
Set up a Connect server.
UUID: redacted
Credentials file: /Users/arun/1password-credentials.json
➜  ~ op connect token create Test --server Connect --vaults redacted
[ERROR] 2023/02/14 00:05:08 Couldn't issue the token: "can't grant access to the vault: You do not have the requested access to vault 'Temp'."
```

If it matters, even after deploying the Connect server on my infrastructure (a Docker container in my MacBook), token creation fails.

Any insights on why this is happening would be great, thank you!

**Comment by mtiller** [comment]
I'm running into the same issue.  Did you ever figure out what was going on?

**Comment by mtiller** [comment]
FYI, my workaround for this was to do this all through the web pages.  I couldn't get the CLI to do it, but via the web application I was able to create a token with the proper permissions without it complaining that I didn't have the permissions needed to create such a token.  Then it was some work to go back and update the `onepassword-token` `Secret` in Kubernetes, but it all seems to be working now.

**Comment by jillianwilson** [comment]
Hi there, thank you for raising this. We have done some investigating and think we have found the issue. We hope to release this fix soon. We'll be sure to update this issue once the fix has been released.

**Comment by ingvarch** [comment]
Passed 1 year. Any updates?

**Comment by Persistent13** [comment]
This is still an issue. I have Full Access rights to the vault and I cannot create a token for it via the CLI.

**Comment by MOmarMiraj** [comment]
Hey Folks,

This was fixed in the CLI v2.15.0 and testing it now I can get it working. Could you please let me know your running a CLI version greater than v2.15.0 and if so, please provide reproduction steps (if its not similar to the one in the issue)

**Comment by volodymyrZotov** [comment]
Closing as should be fixed in CLI v2.15.0 and higher. 

In case of any issue, please drop a message in this thread and I'll re-open the issue.
